spring.application.name=meubles-backend
server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://db.tyfiqegwjdynefehgefr.supabase.co:5432/postgres?user=postgres&password=osNpqZbOGfYdtISZ




spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false